package com.unideh.roomrevenue.roomrevenue.models;

public enum Item {
    DESAYUNO_CONTINENTAL,
    DESAYUNO_AMERICANO,
    OMELETTE_ESPECIAL,
    WAFFLES_CON_FRUTAS,

    //PLATOS PRINCIPALES
    FILETE_SALMON,
    PASTA_CARBONADA,
    POLLO_CURRY,
    ENSALADA_CESAR,
    //BEBIDAS
    CAFE_PREMIUM,
    JUGO_NATURAL,
    COCTEL,
    VINO_TINTO,
    CERVEZA_ARTESANAL,
    //LIMPIEZA Y MANTENIMIENTO,
    CAMBIO_SABANAS,
    TOALLAS_ADICIONALES,
    LIMPIEZA_COMPLETA,
    MANTENIMIENTO,

    //ACTIVIDADES Y SPA
    MASAJE_RELAJANTE,
    FACIAL_REJUVENECEDOR,
    GIMNASIO,
    CLASE_YOGA

}
